// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: jwt.tk.proto

package tkjwtpb

import (
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	api "github.com/ikaiguang/srv_toolkit/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// JwtActiveStatus 活动状态
type JwtActiveStatus int32

const (
	JwtActiveStatus_active_status_unknown JwtActiveStatus = 0 // 未知
	JwtActiveStatus_active_status_valid   JwtActiveStatus = 1 // 有效的(激活用户)
	JwtActiveStatus_active_status_temp    JwtActiveStatus = 2 // 临时的(临时用户：token可设置过期时间)
	JwtActiveStatus_active_status_access  JwtActiveStatus = 3 // 白名单(特殊用户)
	JwtActiveStatus_active_status_deny    JwtActiveStatus = 4 // 黑名单(非法登录)
	JwtActiveStatus_active_status_deleted JwtActiveStatus = 5 // 软删除(无效用户)
	JwtActiveStatus_active_status_invalid JwtActiveStatus = 6 // 无效的(无效用户)
)

// Enum value maps for JwtActiveStatus.
var (
	JwtActiveStatus_name = map[int32]string{
		0: "active_status_unknown",
		1: "active_status_valid",
		2: "active_status_temp",
		3: "active_status_access",
		4: "active_status_deny",
		5: "active_status_deleted",
		6: "active_status_invalid",
	}
	JwtActiveStatus_value = map[string]int32{
		"active_status_unknown": 0,
		"active_status_valid":   1,
		"active_status_temp":    2,
		"active_status_access":  3,
		"active_status_deny":    4,
		"active_status_deleted": 5,
		"active_status_invalid": 6,
	}
)

func (x JwtActiveStatus) Enum() *JwtActiveStatus {
	p := new(JwtActiveStatus)
	*p = x
	return p
}

func (x JwtActiveStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JwtActiveStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_jwt_tk_proto_enumTypes[0].Descriptor()
}

func (JwtActiveStatus) Type() protoreflect.EnumType {
	return &file_jwt_tk_proto_enumTypes[0]
}

func (x JwtActiveStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JwtActiveStatus.Descriptor instead.
func (JwtActiveStatus) EnumDescriptor() ([]byte, []int) {
	return file_jwt_tk_proto_rawDescGZIP(), []int{0}
}

// JwtAuthInfo token auth info
type JwtAuthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId  string       `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`        // 授权id
	Platform api.Platform `protobuf:"varint,2,opt,name=platform,proto3,enum=tkpb.Platform" json:"platform,omitempty"` // 平台
	Et       int64        `protobuf:"varint,3,opt,name=et,proto3" json:"et,omitempty"`                                // 失效时间(时间戳:秒)
	Ct       int64        `protobuf:"varint,4,opt,name=ct,proto3" json:"ct,omitempty"`                                // 创建时间(时间戳:秒)
	Mt       int64        `protobuf:"varint,5,opt,name=mt,proto3" json:"mt,omitempty"`                                // 修改时间(时间戳:秒)
}

func (x *JwtAuthInfo) Reset() {
	*x = JwtAuthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwt_tk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtAuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtAuthInfo) ProtoMessage() {}

func (x *JwtAuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_tk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtAuthInfo.ProtoReflect.Descriptor instead.
func (*JwtAuthInfo) Descriptor() ([]byte, []int) {
	return file_jwt_tk_proto_rawDescGZIP(), []int{0}
}

func (x *JwtAuthInfo) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *JwtAuthInfo) GetPlatform() api.Platform {
	if x != nil {
		return x.Platform
	}
	return api.Platform_platform_unknown
}

func (x *JwtAuthInfo) GetEt() int64 {
	if x != nil {
		return x.Et
	}
	return 0
}

func (x *JwtAuthInfo) GetCt() int64 {
	if x != nil {
		return x.Ct
	}
	return 0
}

func (x *JwtAuthInfo) GetMt() int64 {
	if x != nil {
		return x.Mt
	}
	return 0
}

// JwtAuthPlatformInfo 平台信息
type JwtAuthPlatformInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platform api.Platform `protobuf:"varint,1,opt,name=platform,proto3,enum=tkpb.Platform" json:"platform,omitempty"` // 平台
	LastTime int64        `protobuf:"varint,2,opt,name=last_time,json=lastTime,proto3" json:"last_time,omitempty"`    // 最后登录时间(时间戳:秒)
}

func (x *JwtAuthPlatformInfo) Reset() {
	*x = JwtAuthPlatformInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwt_tk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtAuthPlatformInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtAuthPlatformInfo) ProtoMessage() {}

func (x *JwtAuthPlatformInfo) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_tk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtAuthPlatformInfo.ProtoReflect.Descriptor instead.
func (*JwtAuthPlatformInfo) Descriptor() ([]byte, []int) {
	return file_jwt_tk_proto_rawDescGZIP(), []int{1}
}

func (x *JwtAuthPlatformInfo) GetPlatform() api.Platform {
	if x != nil {
		return x.Platform
	}
	return api.Platform_platform_unknown
}

func (x *JwtAuthPlatformInfo) GetLastTime() int64 {
	if x != nil {
		return x.LastTime
	}
	return 0
}

// JwtAdminInfo 管理员信息
type JwtAdminInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                     // 用户id
	Uuid        string          `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`                                                                  // 用户uuid
	Username    string          `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                                                          // 用户名
	Nickname    string          `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`                                                          // 昵称
	Phone       string          `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`                                                                // 电话号码
	Any         *any.Any        `protobuf:"bytes,99,opt,name=any,proto3" json:"any,omitempty"`                                                                   // any
	TokenStatus JwtActiveStatus `protobuf:"varint,100,opt,name=token_status,json=tokenStatus,proto3,enum=tkjwtpb.JwtActiveStatus" json:"token_status,omitempty"` // 活动状态
	TokenSecret string          `protobuf:"bytes,101,opt,name=token_secret,json=tokenSecret,proto3" json:"token_secret,omitempty"`                               // 授权密码
}

func (x *JwtAdminInfo) Reset() {
	*x = JwtAdminInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwt_tk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtAdminInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtAdminInfo) ProtoMessage() {}

func (x *JwtAdminInfo) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_tk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtAdminInfo.ProtoReflect.Descriptor instead.
func (*JwtAdminInfo) Descriptor() ([]byte, []int) {
	return file_jwt_tk_proto_rawDescGZIP(), []int{2}
}

func (x *JwtAdminInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JwtAdminInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *JwtAdminInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JwtAdminInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *JwtAdminInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *JwtAdminInfo) GetAny() *any.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

func (x *JwtAdminInfo) GetTokenStatus() JwtActiveStatus {
	if x != nil {
		return x.TokenStatus
	}
	return JwtActiveStatus_active_status_unknown
}

func (x *JwtAdminInfo) GetTokenSecret() string {
	if x != nil {
		return x.TokenSecret
	}
	return ""
}

var File_jwt_tk_proto protoreflect.FileDescriptor

var file_jwt_tk_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6a, 0x77, 0x74, 0x2e, 0x74, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x74, 0x6b, 0x6a, 0x77, 0x74, 0x70, 0x62, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x6b, 0x61, 0x69, 0x67, 0x75, 0x61, 0x6e, 0x67, 0x2f, 0x73, 0x72, 0x76, 0x5f, 0x74, 0x6f, 0x6f,
	0x6c, 0x6b, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x0b, 0x4a, 0x77, 0x74, 0x41, 0x75, 0x74,
	0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64,
	0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x74, 0x6b, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x6d, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x6d, 0x74, 0x22, 0x5e, 0x0a, 0x13,
	0x4a, 0x77, 0x74, 0x41, 0x75, 0x74, 0x68, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x74, 0x6b, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12,
	0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x88, 0x02, 0x0a,
	0x0c, 0x4a, 0x77, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x26, 0x0a, 0x03, 0x61, 0x6e, 0x79, 0x18, 0x63, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x03, 0x61, 0x6e, 0x79, 0x12, 0x3b, 0x0a, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e,
	0x74, 0x6b, 0x6a, 0x77, 0x74, 0x70, 0x62, 0x2e, 0x4a, 0x77, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2a, 0xc5, 0x01, 0x0a, 0x0f, 0x4a, 0x77, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x15, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x75, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x01, 0x12,
	0x16, 0x0a, 0x12, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x5f, 0x74, 0x65, 0x6d, 0x70, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10,
	0x03, 0x12, 0x16, 0x0a, 0x12, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x5f, 0x64, 0x65, 0x6e, 0x79, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x10, 0x05, 0x12, 0x19, 0x0a, 0x15, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x06, 0x42,
	0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6b,
	0x61, 0x69, 0x67, 0x75, 0x61, 0x6e, 0x67, 0x2f, 0x73, 0x72, 0x76, 0x5f, 0x74, 0x6f, 0x6f, 0x6c,
	0x6b, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6a, 0x77, 0x74, 0x3b, 0x74, 0x6b, 0x6a, 0x77,
	0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jwt_tk_proto_rawDescOnce sync.Once
	file_jwt_tk_proto_rawDescData = file_jwt_tk_proto_rawDesc
)

func file_jwt_tk_proto_rawDescGZIP() []byte {
	file_jwt_tk_proto_rawDescOnce.Do(func() {
		file_jwt_tk_proto_rawDescData = protoimpl.X.CompressGZIP(file_jwt_tk_proto_rawDescData)
	})
	return file_jwt_tk_proto_rawDescData
}

var file_jwt_tk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jwt_tk_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_jwt_tk_proto_goTypes = []interface{}{
	(JwtActiveStatus)(0),        // 0: tkjwtpb.JwtActiveStatus
	(*JwtAuthInfo)(nil),         // 1: tkjwtpb.JwtAuthInfo
	(*JwtAuthPlatformInfo)(nil), // 2: tkjwtpb.JwtAuthPlatformInfo
	(*JwtAdminInfo)(nil),        // 3: tkjwtpb.JwtAdminInfo
	(api.Platform)(0),           // 4: tkpb.Platform
	(*any.Any)(nil),             // 5: google.protobuf.Any
}
var file_jwt_tk_proto_depIdxs = []int32{
	4, // 0: tkjwtpb.JwtAuthInfo.platform:type_name -> tkpb.Platform
	4, // 1: tkjwtpb.JwtAuthPlatformInfo.platform:type_name -> tkpb.Platform
	5, // 2: tkjwtpb.JwtAdminInfo.any:type_name -> google.protobuf.Any
	0, // 3: tkjwtpb.JwtAdminInfo.token_status:type_name -> tkjwtpb.JwtActiveStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_jwt_tk_proto_init() }
func file_jwt_tk_proto_init() {
	if File_jwt_tk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jwt_tk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtAuthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwt_tk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtAuthPlatformInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwt_tk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtAdminInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jwt_tk_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jwt_tk_proto_goTypes,
		DependencyIndexes: file_jwt_tk_proto_depIdxs,
		EnumInfos:         file_jwt_tk_proto_enumTypes,
		MessageInfos:      file_jwt_tk_proto_msgTypes,
	}.Build()
	File_jwt_tk_proto = out.File
	file_jwt_tk_proto_rawDesc = nil
	file_jwt_tk_proto_goTypes = nil
	file_jwt_tk_proto_depIdxs = nil
}
